### ISSUE TITLE
error

### ISSUE THREAD

**Issue by memosize** [hadesh/tripdemo#2]
MovingAnnotationView.h 引用头文件MAMapKit/MAMapKit.h  提示找不到

**Comment by hadesh** [comment]
pod install 了么？

**Comment by memosize** [comment]
安装了几次不行，我删了重新装不报错了，运行之后提示INCALID_USER_SCODE ,我在天津 点击那个选择终点 没有用，控制台打印the city has not been located,而且一直在定位中。

**Comment by memosize** [comment]
我的，忘记换自己的apikey了
